spring.cloud.azure.cosmos.endpoint=https://cne-groep12-db.documents.azure.com:443/
spring.cloud.azure.cosmos.database=CNE-GROEP12-DB
spring.cloud.azure.cosmos.request-timeout=10000
spring.cloud.azure.cosmos.connection-timeout=10000