spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT}
spring.cloud.azure.cosmos.key=${COSMOS_KEY}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE}
spring.cloud.azure.cosmos.populate-query-metrics=false
spring.cloud.azure.cosmos.consistency-level=SESSION

# REDIS CACHE
spring.cache.type=redis

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true