spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT}
spring.cloud.azure.cosmos.key=${COSMOS_KEY}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE}
spring.cloud.azure.cosmos.populate-query-metrics=false
spring.cloud.azure.cosmos.consistency-level=SESSION

