server:
  port: 8080

spring:
  application:
    name: cloudnativeteam12

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessdb

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ""

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001

jwt:
  secret-key: JCDGzgGzvVT52dx1fa7eg1659lgOd15Sr7ceSCyao2q
